version: "3.8"
services:
  traefik:
    build: .
    container_name: traefik
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic:/dynamic
      - ./config:/config:ro
      - ./acme:/acme
      - ./logs:/logs
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./certs:/certs:ro
    env_file:
      - .env
    command:
      - "--configFile=/traefik.yml"
    entrypoint: ["/bin/sh", "/entrypoint.sh"]