
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websec
          scheme: https
          permanent: true
  websec:
    address: ":443"

  
providers:
  file:
    directory: "/dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "matei8787@gmail.com"
      storage: "/acme/acme.json"
      httpChallenge:
        entryPoint: web

log:
  level: INFO
  filePath: /logs/traefik.log

accessLog:
  filePath: /logs/access.log
  bufferingSize: 100